# Ambiente de produ��o
APP_ENV=prod

# Database (PROD)
# Railway
DATABASE_URL=jdbc:postgresql://caboose.proxy.rlwy.net:37046/railway?sslmode=require&gssEncMode=disable
DATABASE_USER=postgres
DATABASE_PASSWORD=mNaZhrioFPGHWDaRvHeDajyDHYZGqLTQ
