apiVersion: v1
kind: Secret
metadata:
  name: pillmind-secrets
  namespace: pillmind-dev
type: Opaque
stringData:
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
  JWT_SECRET: "pillmind-secret-key-change-in-production-min-256-bits-very-secure"
